CMDS:=build touch install clean realclean
$(CMDS):	FORCE

build:

touch:
	@echo '(touch target not yet implemented)'

install: 
	@echo '(install target not yet implemented)'

clean:	
	rm -f *~

realclean:	clean

.PHONY:	FORCE


